language: cpp

# blacklist
branches:
  except:
    - master

# whitelist
branches:
  only:
    - travis-test

compiler:
  - gcc
  - clang

before_script:
  - cd DeepLearningSuite
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
