language: cpp

# blacklist
branches:
  except:
    - master

# whitelist
branches:
  only:
    - travis-test


os:
  - linux
  - osx

sudo: required
dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost rapidjson glog yaml-cpp qt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install opencv ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rapidjson-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libboost-dev libboost-filesystem-dev libboost-system-dev libboost-program-options-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgoogle-glog-dev libyaml-cpp-dev qt5-default libqt5svg5-dev ; fi
  - sudo pip install numpy
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash install_opencv.sh ; fi

before_script:
  - cd DeepLearningSuite
  - mkdir build
  - cd build
  - cmake ..

script: make

after_success:
  - bash ../package.sh
  - ls -lh ../out/* # Assuming you have some files in out/ that you would like to upload
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ../out/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
